### ISSUE TITLE
Corriger l'espace dans le log sur les deux derniers champs

### ISSUE THREAD

**Issue by Rimeli** [Rimeli/M1-S1-PR-Projet#28]

**Comment by Raimito** [comment]
J'ai ajouté les 2 lignes pour faire l'espace dans le log entre les champs là où y'a les lignes

strcat(result, token[0]);
strcat(result, " ");
strcat(result, token[1]);
strcat(result, " ");
strcat(result, token[2]);

Je fais le comment pour éviter de merge ma version sur un nouveau truc

**Comment by Anaas75** [comment]
Je viens de le faire ...
